# Generated by Django 5.2.5 on 2025-08-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_game_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_color',
            field=models.CharField(default='w', max_length=1),
        ),
    ]
