# Generated by Django 5.2.5 on 2025-08-26 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_game_player_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='GamePvsAI',
        ),
    ]
