# Generated by Django 5.2.5 on 2025-08-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_game_gamepvsai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepvsai',
            name='player_color',
            field=models.CharField(default='white', max_length=5),
        ),
    ]
