# Generated by Django 5.2.5 on 2025-08-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_gamepvsai_player_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepvsai',
            name='move_count',
            field=models.IntegerField(default=1),
        ),
    ]
