# Generated by Django 5.2.5 on 2025-08-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gamepvsai_move_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepvsai',
            name='last_move_from',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='gamepvsai',
            name='last_move_to',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
