# Generated by Django 5.2.5 on 2025-09-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_gamepvsai_last_move_from_gamepvsai_last_move_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepvsai',
            name='castle_lb',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gamepvsai',
            name='castle_lw',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gamepvsai',
            name='castle_sb',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gamepvsai',
            name='castle_sw',
            field=models.BooleanField(default=True),
        ),
    ]
