# Generated by Django 5.2.5 on 2025-09-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_gamepvsai_castle_lb_gamepvsai_castle_lw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepvsai',
            name='king_b',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='gamepvsai',
            name='king_w',
            field=models.IntegerField(default=60),
        ),
    ]
